### ISSUE TITLE
Wire.h workaround?

### ISSUE THREAD

**Issue by Blimpyway** [ermtl/Open-Source-Ventilator#10]
Is there any problem with overwriting Wire.h file with the fixed jm_Wire.h? 

I mean besides the fact an eventual arduino IDE upgrade will replace back the wrong one?

**Comment by ermtl** [comment]
Yes, that is another solution, however I did not want to tell people to start patching Arduino's libraries.
As of now, the jm_Wire solution seems the easiest.
