### ISSUE TITLE
USB serial command CV/CP not working

### ISSUE THREAD

**Issue by Bootpanic** [ermtl/Open-Source-Ventilator#14]
Lines 863 and 864 of OpenSourceVentilator.ino
if (ch='V') CVmode=true; 
if (ch='P') CVmode=false;

Should be changed to:
if (ch=='V') CVmode=true; 
if (ch=='P') CVmode=false;

**Comment by ermtl** [comment]
Oups, nice catch !
thanks for letting me know, it's corrected for version 0.17 a few hours from now !
