### ISSUE TITLE
Compiling on ESP32 fails: 'byte alarm' redeclared as different kind of symbol

### ISSUE THREAD

**Issue by frippe75** [ermtl/Open-Source-Ventilator#25]
Not sure the intention is to support ESP32 at some point. Ongoing work to create PCB for this project has both the Arudino Nano and the ESP32.

Tried to compile for ESP32 and got:
`'byte alarm' redeclared as different kind of symbol`

There has also been ongoing discussion to structure the code differently.
A simple solution would be to place alarm in a struct. 
Tried to look into the variable collision really fast but could not identify it.
A simple renaming would also work.

Not sure which way to go so I didn't create a PR for this.

**Comment by ermtl** [comment]
@frippe75 alarm has been renamed alarmNum to avoid a reserved name. Does it solve the issue ?
