### ISSUE TITLE
Display not showing complete welcome and not hopping between values

### ISSUE THREAD

**Issue by Bootpanic** [ermtl/Open-Source-Ventilator#27]
I think you forgot a "#define dispMenus     // Alternate displays must also enable this"
between lines 357 and 358.

#ifdef BoschBMxSensor
#ifndef I2C
#define I2C
#endif
#endif

Thanks
Keep up the good work!

**Comment by ermtl** [comment]
It was not needed in BoschBMP180Sensor. Removed, thanks for noticing.
I close the issue.
