### ISSUE TITLE
Use symbolic constants for breathing phases

### ISSUE THREAD

**Issue by grifarais** [ermtl/Open-Source-Ventilator#32]
It would help to understand the code if the different values assigned to breathPhase were defined as symbolic constants or enum. I can generate a pull request if required. Here's how I've understood the code:
typedef enum {
  PHASE_START = 0,
  PHASE_INSPIRATION = 1,
  PHASE_EXPIRATION = 2,
  PHASE_SYNC = 3,
  PHASE_END = 4
} breathPhase_t;

**Comment by ermtl** [comment]
Hi, a major new version is coming, and will have this:

`#define breathPhaseStart           0     // In this phase, all the data for the next breathing cycle are calculated

#define breathPhasePlanedBreathIn  1     // In this phase the motor movement starts  with the programmed values for as long as the planned pressure is not reached

#define breathPhaseStartBreathOut  2     // In this phase, the breath out is calculated and started

#define breathPhasePlanedBreathOut 3     // In this phase the motor movement starts  with the programmed values for as long as the motor position is above 0

#define breathPhasePatientTrigger  4     // In this phase, the patient has inspired (rapid pressure drop)) thus starting a new assisted cycle `
