### ISSUE TITLE
Document how to configure and upload the code to an Arduino

### ISSUE THREAD

**Issue by ZakCodes** [ermtl/Open-Source-Ventilator#4]
It would be nice to specify in the README.md or in the CONTRIBUTING.md what libraries to install (and maybe their versions) for this project to compile as well as how to compile and upload this project.

There could be links to the following official Arduino guides:
* How to install the Arduino IDE
  * [Windows](https://www.arduino.cc/en/guide/windows)
  * [Linux](https://www.arduino.cc/en/guide/linux)
  * [MacOS X](https://www.arduino.cc/en/Guide/MacOSX)
* [How to use the Arduino IDE](https://www.arduino.cc/en/Guide/Environment#toc9), among other things, this explains how to upload to a board
* [How to install libraries](https://www.arduino.cc/en/guide/libraries)

There should also be more explanations on how to disable certain sensors in the code. It's really a great feature and people really need to know how to use it.

<br>

I would also like to point out that the [Arduino IDE] is awful and that using [VS Code] with the [Arduino extension][Arduino VS Code] should be considered, since it offers autocompletion. However, from my experience with the ESP32 and ESP8266, compile times are longer when using it.

Another option would be to use [PlatformIO] with the [Arduino Framework](https://docs.platformio.org/en/latest/frameworks/arduino.html) on [VS Code]. This is my favorite one, because [PlatformIO] has a configuration file which would allow people who want to compile and upload this project to a board to enter a single command in the terminal or to click a single button in [VS Code] to [download all the required Arduino libraries with the right version for the project](https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps). Their extension also offers better autocompletion than the [Arduino extension for VS Code][Arduino VS Code]. However, [PlatformIO] has a very specific folder structure for code which I believe is great, but would require this repository to be reorganized a little and it wouldn't be compatible with the [Arduino IDE] or the [Arduino extension for VS Code][Arduino VS Code] anymore.

[Arduino IDE]: https://www.arduino.cc/en/Main/Software
[VS Code]: https://code.visualstudio.com/
[PlatformIO]: https://platformio.org/
[Arduino VS Code]: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino

**Comment by ermtl** [comment]
Arduino, for better or worst, is what a majority of people use and that's it's greatest strength. Going to any other platform would severely limit audience and, as you mention, would cause issues with the regular Arduino platform. Also, it's all happening in a rushed situation, I would like to keep it simple.
